project_id: '570007'
api_token_env: 057f6fe5ee1450981a4192c910dd3ad0077353321e7125c30675c8876a62609fca841504e8496585
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /i18n/pt-BR/**/*
    translation: /i18n/pt-BR/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # Blog Markdown files
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%